spring:
  application:
    name: notification-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        notification-in:
          destination: notification
          content-type: application/json
        notification-out:
          destination: notification
          content-type: application/json
          
server:
  port: 6262 

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    ip-address: true
